services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 20
      

  # Redis stack w/ vector search enabled

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight UI
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # Airflow init

  airflow-init:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./runner.py:/opt/airflow/project/runner.py
      - ./data:/opt/airflow/project/data
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email nicholas.nehemia95@gmail.com || true
      "
    restart: "no"

  airflow-webserver:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "j7duz280Bn_eZ8YsobCSSWF3vOu_zJQp5csdwiIbWEY"
      AIRFLOW_CONN_SKI_PG: postgresql://airflow:airflow@postgres:5432/ski_pipeline
      PYTHONPATH: /opt/airflow/project
    volumes:
      - ./dags:/opt/airflow/dags
      - ./runner.py:/opt/airflow/project/runner.py
      - ./data:/opt/airflow/project/data
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    build: .
    hostname: airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/project
      AIRFLOW__WEBSERVER__SECRET_KEY: "j7duz280Bn_eZ8YsobCSSWF3vOu_zJQp5csdwiIbWEY"
      AIRFLOW_CONN_SKI_PG: postgresql://airflow:airflow@postgres:5432/ski_pipeline
    volumes:
      - ./dags:/opt/airflow/dags
      - ./runner.py:/opt/airflow/project/runner.py
      - ./data:/opt/airflow/project/data
    command: airflow scheduler

volumes:
  postgres-db-volume:
  redis-data:
